{
 "title": "BACULA_ALL_IN_ONE",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "10s",
 "panels": [
  { "title": "Bacula_ONE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 1, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Bacula" },
     "group": { "filter": "BACULA" },
     "host": { "filter": "Bacula_ONE" },
     "item": { "filter": "Bacula Director is running" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total de Clientes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "rawSql": "select count(Name) from client" }
   ]
  },
  {
   "title": "Backups Concluidos",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(jobstatus) from job\r\nwhere starttime > now() - interval '24h' and jobstatus = 'T'"
    }
   ]
  },
  {
   "title": "Backups Rodando",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(jobstatus) from job\r\nwhere starttime > now() - interval '24h' and jobstatus = 'R' or jobstatus = 'C'"
    }
   ]
  },
  {
   "title": "Volumes iSCI - Abertos",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(volumename) FROM media\r\nwhere volumename like '%iSCSI%' and volstatus = 'Append'"
    }
   ]
  },
  {
   "title": "Backups Abortados",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(jobstatus) from job\r\nwhere starttime > now() - interval '24h' and jobstatus = 'A' or jobstatus = 'E' "
    }
   ]
  },
  {
   "title": "CONSUMO REDE",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "host": { "filter": "Bacula_ONE" },
     "item": {
      "filter": "Incoming network traffic on eno1"
     },
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "SELECT SUM(jobbytes) AS Bytes FROM Job WHERE clientid='3';\r\n\r\n",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "BACULA" },
     "host": { "filter": "Bacula_ONE" },
     "item": {
      "filter": "Outgoing network traffic on eno1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Utilização do Storage - INTERNO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n SUM(VolBytes) \nFROM \n Media\nwhere\nmediatype='File172';\n"
    }
   ]
  },
  {
   "title": "Backups Falhos",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "rawSql": "select name from job\r\nwhere starttime > now() - interval '24h' and jobstatus = 'A' or jobstatus = 'E' \r\nlimit 5",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Volumes ARQ - Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT maxvols FROM pool\r\nwhere name = 'FileARQ'"
    }
   ]
  },
  {
   "title": "Volumes iSCI - FULL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(volumename) FROM media\r\nwhere volumename like '%iSCSI%' and volstatus = 'Full'"
    }
   ]
  },
  {
   "title": "Volumes ARQ - FULL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(volumename) FROM media\r\nwhere volumename not like '%iSCSI%' and volumename like '%ARQ%' and volstatus = 'Full'"
    }
   ]
  },
  {
   "title": "Volumes ARQ - Abertos",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(volumename) FROM media\r\nwhere volumename not like '%iSCI%' and volumename like '%ARQ%' and volstatus = 'Append'"
    }
   ]
  },
  {
   "title": "Utilização do Storage - iSCSI",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n SUM(VolBytes) \nFROM \n Media\nwhere\nmediatype='FileiSCSI';\n"
    }
   ]
  },
  {
   "title": "Volumes iSCI - Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT maxvols FROM pool\r\nwhere name = 'FileARQ-iSCSI'"
    }
   ]
  },
  { "title": "Bacula_TWO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 1, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Bacula" },
     "group": { "filter": "BACULA" },
     "host": { "filter": "Bacula_TWO" },
     "item": { "filter": "Bacula Director is running" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total de Clientes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "rawSql": "select count(Name) from client" }
   ]
  },
  {
   "title": "Volumes SQL - FULL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(volumename) FROM media\r\nwhere volumename not like '%SQL2%' and volumename like '%SQL%' and volstatus = 'Full'"
    }
   ]
  },
  {
   "title": "Backups Rodando",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(jobstatus) from job\r\nwhere starttime > now() - interval '24h' and jobstatus = 'R' or jobstatus = 'C'"
    }
   ]
  },
  {
   "title": "Backups Concluidos",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(jobstatus) from job\r\nwhere starttime > now() - interval '24h' and jobstatus = 'T'"
    }
   ]
  },
  {
   "title": "Backups Abortados",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(jobstatus) from job\r\nwhere starttime > now() - interval '24h' and jobstatus = 'A'"
    }
   ]
  },
  {
   "title": "CONSUMO REDE",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "host": { "filter": "Bacula_TWO" },
     "item": {
      "filter": "Incoming network traffic on eno1"
     },
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "SELECT SUM(jobbytes) AS Bytes FROM Job WHERE clientid='3';\r\n\r\n",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "BACULA" },
     "host": { "filter": "Bacula_TWO" },
     "item": {
      "filter": "Outgoing network traffic on eno1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Utilização do Storage - INTERNO",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 8 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n SUM(VolBytes) \nFROM \n Media\nwhere\nmediatype='File172';\n"
    }
   ]
  },
  {
   "title": "Backups Falhos",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 8 },
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "rawSql": "select name from job\r\nwhere starttime > now() - interval '24h' and jobstatus = 'A' \r\nlimit 5",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Volumes ARQ - Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT maxvols FROM pool\r\nwhere name = 'FileSQL'"
    }
   ]
  },
  {
   "title": "Volumes SQL - Abertos",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(volumename) FROM media\r\nwhere volumename not like '%SQL2%' and volumename like '%SQL%' and volstatus = 'Append'"
    }
   ]
  },
  { "title": "Bacula_THREE", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 1, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Bacula" },
     "group": { "filter": "BACULA" },
     "host": { "filter": "Bacula_THREE" },
     "item": { "filter": "Bacula Director is running" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total de Clientes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "rawSql": "select count(Name) from client" }
   ]
  },
  {
   "title": "Volumes - FULL",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(volumename) FROM media\r\nwhere volumename like '%Vol-%' and volstatus = 'Full'"
    }
   ]
  },
  {
   "title": "Backups Rodando",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(jobstatus) from job\r\nwhere starttime > now() - interval '24h' and jobstatus = 'R' or jobstatus = 'C'"
    }
   ]
  },
  {
   "title": "Backups Concluidos",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(jobstatus) from job\r\nwhere starttime > now() - interval '24h' and jobstatus = 'T'"
    }
   ]
  },
  {
   "title": "Backups Abortados",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(jobstatus) from job\r\nwhere starttime > now() - interval '24h' and jobstatus = 'A'"
    }
   ]
  },
  {
   "title": "CONSUMO REDE",
   "type": "graph",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 15 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "host": { "filter": "Bacula_THREE" },
     "item": {
      "filter": "Incoming network traffic on eno1"
     },
     "options": {
      "showDisabledItems": false
     },
     "rawSql": "SELECT SUM(jobbytes) AS Bytes FROM Job WHERE clientid='3';\r\n\r\n",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "BACULA" },
     "host": { "filter": "Bacula_THREE" },
     "item": {
      "filter": "Outgoing network traffic on eno1"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Utilização do Storage - INTERNO",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 15 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n SUM(VolBytes) \nFROM \n Media\nwhere\nmediatype='File172';\n"
    }
   ]
  },
  {
   "title": "Backups Falhos",
   "type": "table",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 15 },
   "targets": [
    {
     "application": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "rawSql": "select name from job\r\nwhere starttime > now() - interval '24h' and jobstatus = 'A' \r\nlimit 5",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Volumes - Total",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT maxvols FROM pool\r\nwhere name = 'File'"
    }
   ]
  },
  {
   "title": "Volumes - Abertos",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT count(volumename) FROM media\r\nwhere volumename like '%Vol-%' and volstatus = 'Append'"
    }
   ]
  }
 ]
}